require('dotenv').config();
const express=require('express');
const cors=require('cors');
const helmet=require('helmet');
const session=require('express-session');
const {Pool}=require('pg');
const {Client,GatewayIntentBits,PermissionsBitField}=require('discord.js');
const app=express();
const PORT=process.env.PORT||3000;
const FRONTEND=(process.env.FRONTEND_ORIGIN||'https://aimfev.github.io').replace(/\/$/,'');
const FRONTEND_URL=FRONTEND+'/bot-dashboard/';
app.set('trust proxy',1);
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:FRONTEND,credentials:true}));
app.use(express.json({limit:'100kb'}));
if(!process.env.SESSION_SECRET){console.error('SESSION_SECRET is missing from Render environment variables.');process.exit(1);}
app.use(session({name:'ducky.sid',secret:process.env.SESSION_SECRET,resave:false,saveUninitialized:false,cookie:{httpOnly:true,secure:true,sameSite:'none',maxAge:7*24*60*60*1000}}));
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}}):null;
let bot=null,botReady=false;
if(process.env.DISCORD_BOT_TOKEN){
bot=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers]});
bot.once('clientReady',()=>{botReady=true;console.log(`DUCKY bot online as ${bot.user.tag}`);});
bot.on('error',e=>console.error('Discord bot error:',e.message));
bot.login(process.env.DISCORD_BOT_TOKEN).catch(e=>console.error('Bot login failed:',e.message));
}else console.warn('DISCORD_BOT_TOKEN is not configured.');
const schema=`
CREATE TABLE IF NOT EXISTS dashboard_settings(guild_id TEXT NOT NULL,module TEXT NOT NULL,config JSONB NOT NULL DEFAULT '{}'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(guild_id,module));
CREATE TABLE IF NOT EXISTS moderation_cases(id BIGSERIAL PRIMARY KEY,guild_id TEXT NOT NULL,actor_id TEXT,target_id TEXT NOT NULL,action TEXT NOT NULL,reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS server_logs(id BIGSERIAL PRIMARY KEY,guild_id TEXT NOT NULL,type TEXT NOT NULL,message TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`;
async function db(sql,args=[]){if(!pool)throw new Error('Database is not configured.');return pool.query(sql,args);}
async function init(){if(!pool){console.warn('DATABASE_URL is not configured.');return;}try{await pool.query(schema);console.log('Database tables checked');}catch(e){console.error('Database init failed:',e.message);}}
init();
function requireAuth(req,res,next){if(!req.session.user)return res.status(401).json({error:'Connect Discord first.'});next();}
function hasManagePermission(g){try{const p=BigInt(g.permissions||'0');return Boolean(g.owner)||(p&BigInt(PermissionsBitField.Flags.Administrator))!==0n||(p&BigInt(PermissionsBitField.Flags.ManageGuild))!==0n;}catch{return false;}}
function canManage(req,id){if(!/^\d{17,20}$/.test(String(id||'')))return false;return(req.session.guilds||[]).some(g=>g.id===String(id)&&hasManagePermission(g));}
function getBotGuild(id){return bot&&botReady?bot.guilds.cache.get(String(id))||null:null;}
async function requireManagedBotGuild(req,res,id){if(!canManage(req,id)){res.status(403).json({error:'You need Manage Server permission for this server.'});return null;}if(!botReady){res.status(503).json({error:'The Discord bot is not online.'});return null;}const g=getBotGuild(id);if(!g){res.status(404).json({error:'Your bot is not installed in this server.'});return null;}return g;}
app.get('/health',(req,res)=>res.json({ok:true,botReady,dbConfigured:Boolean(pool),service:'DUCKY API'}));
app.get('/auth/discord/url',(req,res)=>{if(!process.env.DISCORD_CLIENT_ID||!process.env.DISCORD_REDIRECT_URI)return res.status(503).json({error:'Discord OAuth environment variables are missing.'});const u=new URL('https://discord.com/oauth2/authorize');u.searchParams.set('client_id',process.env.DISCORD_CLIENT_ID);u.searchParams.set('redirect_uri',process.env.DISCORD_REDIRECT_URI);u.searchParams.set('response_type','code');u.searchParams.set('scope','identify guilds');res.json({url:u.toString()});});
app.get('/auth/discord/callback',async(req,res)=>{try{const code=req.query.code;if(!code)return res.redirect(FRONTEND_URL+'?login=cancelled');const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID||'',client_secret:process.env.DISCORD_CLIENT_SECRET||'',grant_type:'authorization_code',code,redirect_uri:process.env.DISCORD_REDIRECT_URI||''})});const token=await tr.json();if(!tr.ok||!token.access_token){console.error('OAuth exchange failed:',token.error||tr.status);return res.status(401).send('Discord authentication failed. Check OAuth configuration and try again.');}const headers={Authorization:`Bearer ${token.access_token}`};const [ur,gr]=await Promise.all([fetch('https://discord.com/api/users/@me',{headers}),fetch('https://discord.com/api/users/@me/guilds',{headers})]);if(!ur.ok||!gr.ok)throw new Error('Could not retrieve your Discord account or servers.');const user=await ur.json(),guilds=await gr.json();if(!user.id||!Array.isArray(guilds))throw new Error('Invalid Discord response.');req.session.regenerate(err=>{if(err){console.error('Session regenerate failed:',err.message);return res.status(500).send('Could not create login session.');}req.session.user={id:user.id,username:user.global_name||user.username,avatar:user.avatar?`https://cdn.discordapp.com/avatars/${user.id}/${user.avatar}.png`:null};req.session.guilds=guilds.filter(hasManagePermission).map(g=>({id:g.id,name:g.name,owner:g.owner,permissions:g.permissions,icon:g.icon}));req.session.save(err=>{if(err){console.error('Session save failed:',err.message);return res.status(500).send('Could not save login session.');}res.redirect(FRONTEND_URL);});});}catch(e){console.error('OAuth callback:',e.message);res.status(500).send('Discord login failed. Check backend environment settings.');}});
app.get('/api/me',requireAuth,(req,res)=>{const guilds=(req.session.guilds||[]).map(g=>({id:g.id,name:g.name,owner:g.owner,icon:g.icon,botInstalled:Boolean(getBotGuild(g.id)),botReady,canManage:true}));res.set('Cache-Control','no-store');res.json({user:req.session.user,guilds,botReady});});
app.post('/api/logout',requireAuth,(req,res)=>{req.session.destroy(e=>{if(e)return res.status(500).json({error:'Could not log out.'});res.clearCookie('ducky.sid',{httpOnly:true,secure:true,sameSite:'none'});res.json({ok:true});});});
app.get('/api/modules/:module',requireAuth,async(req,res)=>{try{const id=String(req.query.guildId||'');const g=await requireManagedBotGuild(req,res,id);if(!g)return;const r=await db('SELECT config,updated_at FROM dashboard_settings WHERE guild_id=$1 AND module=$2',[id,req.params.module]);res.json({config:r.rows[0]?.config||{},updatedAt:r.rows[0]?.updated_at||null});}catch(e){console.error('Read module failed:',e.message);res.status(500).json({error:'Could not read module settings.'});}});
app.put('/api/modules/:module',requireAuth,async(req,res)=>{try{const id=String(req.body.guildId||'');const g=await requireManagedBotGuild(req,res,id);if(!g)return;const config={features:Array.isArray(req.body.features)?req.body.features:[]};await db(`INSERT INTO dashboard_settings(guild_id,module,config) VALUES($1,$2,$3) ON CONFLICT(guild_id,module) DO UPDATE SET config=EXCLUDED.config,updated_at=NOW()`,[id,req.params.module,JSON.stringify(config)]);res.json({ok:true,message:'Saved module configuration.'});}catch(e){console.error('Save module failed:',e.message);res.status(500).json({error:'Could not save module settings.'});}});
app.put('/api/modules/:module/config',requireAuth,async(req,res)=>{try{const id=String(req.body.guildId||'');const g=await requireManagedBotGuild(req,res,id);if(!g)return;const config={channelId:String(req.body.channelId||''),details:String(req.body.details||'').slice(0,4000)};await db(`INSERT INTO dashboard_settings(guild_id,module,config) VALUES($1,$2,$3) ON CONFLICT(guild_id,module) DO UPDATE SET config=EXCLUDED.config,updated_at=NOW()`,[id,req.params.module,JSON.stringify(config)]);res.json({ok:true,message:'Saved configuration.'});}catch(e){console.error('Save config failed:',e.message);res.status(500).json({error:'Could not save configuration.'});}});
app.get('/api/moderation',requireAuth,async(req,res)=>{try{const id=String(req.query.guildId||'');const g=await requireManagedBotGuild(req,res,id);if(!g)return;const r=await db(`SELECT id,actor_id AS "actorId",target_id AS "targetId",action,reason,created_at AS "createdAt" FROM moderation_cases WHERE guild_id=$1 ORDER BY id DESC LIMIT 100`,[id]);res.json({cases:r.rows});}catch(e){console.error('Moderation history failed:',e.message);res.status(500).json({error:'Could not load moderation history.'});}});
app.post('/api/moderation',requireAuth,async(req,res)=>{try{const {guildId,action,targetId,reason,durationMinutes}=req.body;const g=await requireManagedBotGuild(req,res,guildId);if(!g)return;if(!['warn','timeout','kick','ban'].includes(action))return res.status(400).json({error:'Unsupported action.'});if(!/^\d{17,20}$/.test(String(targetId||'')))return res.status(400).json({error:'Enter a valid Discord user ID.'});const why=String(reason||'No reason provided').slice(0,500);const member=action==='ban'?await g.members.fetch({user:String(targetId),force:false}).catch(()=>null):await g.members.fetch(String(targetId)).catch(()=>null);if(action!=='ban'&&!member)return res.status(404).json({error:'Member not found in this server.'});if(action==='warn'){/* Record warning; no DM is sent. */}else if(action==='timeout'){if(!member.moderatable)return res.status(403).json({error:'Bot cannot timeout this member. Check role hierarchy and permissions.'});const mins=Math.max(1,Math.min(40320,Number(durationMinutes)||10));await member.timeout(mins*60000,why);}else if(action==='kick'){if(!member.kickable)return res.status(403).json({error:'Bot cannot kick this member. Check role hierarchy and permissions.'});await member.kick(why);}else if(action==='ban'){if(member&&!member.bannable)return res.status(403).json({error:'Bot cannot ban this member. Check role hierarchy and permissions.'});await g.members.ban(String(targetId),{reason:why});}await db('INSERT INTO moderation_cases(guild_id,actor_id,target_id,action,reason) VALUES($1,$2,$3,$4,$5)',[String(guildId),req.session.user.id,String(targetId),action,why]);await db('INSERT INTO server_logs(guild_id,type,message) VALUES($1,$2,$3)',[String(guildId),'moderation',`${action} ${targetId}: ${why}`]);res.json({ok:true,message:action==='warn'?'Warning recorded (no DM sent).':`${action} action completed.`});}catch(e){console.error('Moderation action failed:',e.message);res.status(500).json({error:'Moderation action failed.'});}});
app.get('/api/logs',requireAuth,async(req,res)=>{try{const id=String(req.query.guildId||'');const g=await requireManagedBotGuild(req,res,id);if(!g)return;const r=await db(`SELECT type,message,created_at AS "createdAt" FROM server_logs WHERE guild_id=$1 ORDER BY id DESC LIMIT 100`,[id]);res.json({logs:r.rows});}catch(e){console.error('Load logs failed:',e.message);res.status(500).json({error:'Could not load server logs.'});}});
app.use((err,req,res,next)=>{console.error('Unhandled request error:',err.message);if(res.headersSent)return next(err);res.status(500).json({error:'Unexpected server error.'});});
app.listen(PORT,()=>console.log(`DUCKY backend listening on ${PORT}`));
